[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "gerber_to_scad"
version = "0.1.0"

[tool.poetry.dependencies]
Django = "^3.2.7"
django-bootstrap3 = "^15.0.0"
django-environ = "^0.7.0"
gunicorn = "^20.1.0"
pcb-tools = "^0.1.6"
python = "^3.9,<3.11"
scipy = "^1.7.1"
solidpython = "^1.1.1"
taskipy = "^1.9.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.taskipy.tasks]
g2s = "python gerber_to_scad/gerber_to_scad.py"
service = "gunicorn --workers 1 --threads 8 gts_service.wsgi"
